### PR TITLE
 pass opts.sync = false into level-live-stream for kv.createReadStream

### PR DESCRIPTION
**Pull request by laduke**
thanks for walking me through this @noffle 

Also threw in passing opts.old through to level-live-steam; let me know if I should drop that commit.

### CODE REVIEW

**Comment by noffle** [comment]
Nice! Could you also write a test that demonstrates that this works as expected?

**Comment by laduke** [comment]
Thought I could sneak through ;)

Let me go find some good ones to copy from. Sounds a little tricky.

**Comment by noffle** [comment]
Here's an idea:

1. create a hyperkv
2. write two values
3. start a live read stream and listen for data from it
4. note those two values being emitted
5. write two more & note them being emitted too

This shows that no sync message came through the stream between old messages and the new ones.

**Comment by laduke** [comment]
Welp, test don't pass without the changes and they do pass after the changes.

**Comment by noffle** [comment]
woo awesome work @laduke! :tada:

**Comment by noffle** [comment]
2.0.4

**Comment by laduke** [comment]
whoa!

**Pull request merged**
